### ISSUE TITLE
Dev setup takes a long time

### ISSUE THREAD

**Issue by sa-** [mojo-data/arrow.mojo#23]
source: https://github.com/mojo-data/arrow.mojo/pull/21#discussion_r1641359528

Making pyenv an optional but recommended dependency should suffice. 
Switching from poetry to uv will allow people install venv's using pip

**Comment by martinvuyk** [comment]
Hi, thanks a lot for the changes. Deleted and tried again and it works with python 3.10 with no  hiccups.
just did (less than 2 minutes):
- virtualenv venv
- source ./venv/bin/activate
- pip install -r requirements.txt
- pip install uv
- make setup
though make setup gives me an error
```text
make: ./.venv/bin/pre-commit: No such file or directory
make: *** [Makefile:24: setup] Error 127
```

**Comment by sa-** [comment]
Ah uv is not a python package it's a rust tool. I think you could install it via pip but I'm not sure why one would. You can see the installation instructions 

If you are creating your own venv and installing via pip then you actually don't need UV.

Alright it fails makefile assumes the folder is called `.venv` and not `venv`. I can add a note for this

**Comment by sa-** [comment]
Ah uv is not a python package it's a rust tool. I think you could install it via pip but I'm not sure why one would. You can see the installation instructions 

If you are creating your own venv and installing via pip then you actually don't need UV.

Alright it fails makefile assumes the folder is called `.venv` and not `venv`. I can add a note for this

Also virtualenv is deprecated. venv comes with Python already. If the venv is recreated on your machine with `python3 -m venv .venv` everything should work

**Comment by sa-** [comment]
I'm closing this issue for now, but if make setup doesn't work after recreating the venv following the above instructions then feel free to reopen the issue. The README is also updated to include this detail

**Comment by martinvuyk** [comment]
> assumes the folder is called .venv and not venv

uv is creating a `.venv` folder though, but now that I see it it says python 3.11 and I'm running on 3.10 globally, so maybe it's because of that. Anyway, testing works which is the most important thing :)
